spring.application.name=etlVisualizer

# Server Configuration
server.port=${PORT:8080}
server.address=0.0.0.0

# MongoDB Atlas Configuration
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}
spring.data.mongodb.auto-index-creation=true

# JWT secret key
jwt.secretKey=${JWT_SECRET_KEY}

# Couchbase credentials
couchbase.username=${COUCHBASE_USERNAME}
couchbase.password=${COUCHBASE_PASSWORD}

debug=true